// Canonical Supabase Database type for the BURS repo.
//
// Generation target: `npx supabase gen types typescript --linked > supabase/types.gen.ts`
// — this file owns the type after the post-launch web (`src/`) deletion. Until
// that delete lands the source of truth still lives at
// `src/integrations/supabase/types.ts` (auto-generated by Lovable on schema
// changes), so this stub re-exports from there to keep the import path stable
// for mobile consumers (mobile/src/types/{garment,outfit}.ts).
//
// Note: `mobile/src/lib/memoryEvents.ts` imports a different domain type
// (`CanonicalStyleMemorySignal` from `src/types/styleMemory`) and is not
// covered by this re-export. That import is permitted by the boundary lint
// rule's `allowTypeImports: true` carve-out and will be inlined into mobile
// when the web tree is deleted.
//
// When `src/` is removed:
// 1. Run the gen-types command above.
// 2. Replace the re-export below with the generated `Database` type.
// 3. The mobile import paths do not change.

export type { Database } from '../src/integrations/supabase/types';
