#!/usr/bin/env node
// translate-locales — drives the translate_locale edge function to produce
// 12 mobile locale dictionaries from en.ts (source) + sv.ts (anchor).
//
// Usage:
//   node mobile/scripts/translate-locales.mjs                # all 12 locales
//   node mobile/scripts/translate-locales.mjs --locales fr,de
//   node mobile/scripts/translate-locales.mjs --only-missing # backfill mode
//   node mobile/scripts/translate-locales.mjs --dry-run      # parse only
//
// Env required (load from mobile/.env.local or process.env):
//   EXPO_PUBLIC_SUPABASE_URL  (or SUPABASE_URL)
//   TRANSLATE_LOCALE_SECRET
//
// Output: mobile/src/i18n/locales/<locale>.ts (overwrites unless --only-missing)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');

export const TARGET_LOCALES = [
  'ar', 'da', 'de', 'es', 'fa', 'fi', 'fr', 'it', 'nl', 'no', 'pl', 'pt',
];

/**
 * Parse a locale file's `Record<string, string>` literal into a JS object.
 * Order-preserving. Strips // line comments + /* block comments first.
 * Accepts single OR double-quoted keys and values; handles backslash-escaped
 * quotes inside values (don\'t).
 */
export function parseLocaleFile(src) {
  let s = src;
  s = s.replace(/\/\*[\s\S]*?\*\//g, '');
  s = s.replace(/^\s*\/\/.*$/gm, '');
  const out = {};
  // key: ('foo' | "foo")  : value: ('...' | "...")
  const re = /(['"])((?:\\.|(?!\1)[^\\])*)\1\s*:\s*(['"])((?:\\.|(?!\3)[^\\])*)\3\s*,?/g;
  let m;
  while ((m = re.exec(s)) !== null) {
    const key = m[2].replace(/\\(['"\\])/g, '$1');
    const val = m[4].replace(/\\(['"\\])/g, '$1');
    out[key] = val;
  }
  return out;
}

export function chunkObject(obj, size) {
  const out = [];
  const keys = Object.keys(obj);
  for (let i = 0; i < keys.length; i += size) {
    const chunk = {};
    for (const k of keys.slice(i, i + size)) chunk[k] = obj[k];
    out.push(chunk);
  }
  return out;
}

const CHUNK_SIZE = 80;

async function callEdge(envUrl, secret, payload) {
  const url = `${envUrl}/functions/v1/translate_locale`;
  // Retry on transport-level errors (ECONNRESET, ETIMEDOUT, etc.). HTTP
  // status errors (502, 413, …) flow through to the caller; only thrown
  // failures hit this retry loop. 3 attempts with linear 2s backoff.
  let lastErr;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'x-translate-secret': secret,
        },
        body: JSON.stringify(payload),
      });
      const text = await res.text();
      let body;
      try { body = JSON.parse(text); } catch { body = { error: 'non-json response', raw: text }; }
      return { status: res.status, body };
    } catch (err) {
      lastErr = err;
      const backoffMs = 2000 * (attempt + 1);
      console.log(`    fetch failed (attempt ${attempt + 1}/3): ${err?.cause?.code || err?.code || err?.message || err}; retrying in ${backoffMs}ms`);
      await new Promise((r) => setTimeout(r, backoffMs));
    }
  }
  // Exhausted retries — return a synthetic 599 so the split-retry layer
  // sees it as a transient and splits the chunk further (eventually
  // falling back to English passthrough at min chunk size).
  return { status: 599, body: { error: `fetch failed after retries: ${lastErr?.cause?.code || lastErr?.message || lastErr}` } };
}

export function renderLocaleFile(locale, dict, opts = {}) {
  const { sourceSha = 'unknown' } = opts;
  const header = `// Auto-generated by mobile/scripts/translate-locales.mjs (${new Date().toISOString().slice(0, 10)}).
// Source: mobile/src/i18n/locales/en.ts (hash ${sourceSha}).
// Voice anchor: mobile/src/i18n/locales/sv.ts.
//
// To regenerate after en.ts grows:
//   node mobile/scripts/translate-locales.mjs --locales ${locale} --only-missing
//
// Append-only convention applies post-generation — never reorder keys.

export const ${locale}: Record<string, string> = {
`;
  const lines = [];
  for (const k of Object.keys(dict)) {
    const v = dict[k];
    // Pick the wrapping quote that doesn't require escaping the value.
    let wrap = "'";
    if (v.includes("'") && !v.includes('"')) wrap = '"';
    let escaped = v;
    if (wrap === "'") escaped = v.replace(/'/g, "\\'");
    else escaped = v.replace(/"/g, '\\"');
    const safeKey = k.replace(/'/g, "\\'");
    lines.push(`  '${safeKey}': ${wrap}${escaped}${wrap},`);
  }
  return header + lines.join('\n') + '\n};\n';
}

/**
 * Translate one chunk. On 502 (typically Gemini truncation on long-string
 * locales like ar/fa), recursively splits the chunk into halves and retries.
 * Stops splitting at MIN_CHUNK_SIZE — any chunk still failing at that size
 * fills its keys with English passthrough so the locale completes instead
 * of crashing the whole orchestrator run.
 */
const MIN_CHUNK_SIZE = 10;
async function translateChunkWithSplit({
  targetLocale, chunk, sv, envUrl, secret, edgeCall, log, depth = 0, chunkLabel,
}) {
  const svRef = {};
  for (const k of Object.keys(chunk)) if (sv[k] !== undefined) svRef[k] = sv[k];
  const { status, body } = await edgeCall(envUrl, secret, {
    target_locale: targetLocale,
    source_keys: chunk,
    sv_reference: svRef,
    chunk_index: 0,
    total_chunks: 1,
  });
  if (status === 200) {
    return { translations: body.translations || {}, missing: body.missing_keys || [] };
  }
  const keys = Object.keys(chunk);
  if (keys.length <= MIN_CHUNK_SIZE) {
    log(`  ${' '.repeat(depth * 2)}[${targetLocale}] ${chunkLabel} (${keys.length} keys) failed at min split — falling back to en for these keys: HTTP ${status}`);
    const passthrough = {};
    for (const k of keys) passthrough[k] = chunk[k];
    return { translations: passthrough, missing: keys };
  }
  const half = Math.ceil(keys.length / 2);
  const left = {}; const right = {};
  for (let i = 0; i < keys.length; i++) (i < half ? left : right)[keys[i]] = chunk[keys[i]];
  log(`  ${' '.repeat(depth * 2)}[${targetLocale}] ${chunkLabel} split: ${keys.length} → ${half} + ${keys.length - half} (HTTP ${status})`);
  const a = await translateChunkWithSplit({ targetLocale, chunk: left, sv, envUrl, secret, edgeCall, log, depth: depth + 1, chunkLabel: chunkLabel + '.L' });
  const b = await translateChunkWithSplit({ targetLocale, chunk: right, sv, envUrl, secret, edgeCall, log, depth: depth + 1, chunkLabel: chunkLabel + '.R' });
  return {
    translations: { ...a.translations, ...b.translations },
    missing: [...a.missing, ...b.missing],
  };
}

export async function translateOneLocale({
  targetLocale,
  source,
  sv,
  envUrl,
  secret,
  log = console.log,
  edgeCall = callEdge,
}) {
  const chunks = chunkObject(source, CHUNK_SIZE);
  const merged = {};
  const allMissing = [];
  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    log(`  [${targetLocale}] chunk ${i + 1}/${chunks.length} (${Object.keys(chunk).length} keys)`);
    const { translations, missing } = await translateChunkWithSplit({
      targetLocale, chunk, sv, envUrl, secret, edgeCall, log,
      chunkLabel: `chunk ${i + 1}/${chunks.length}`,
    });
    for (const k of Object.keys(translations)) merged[k] = translations[k];
    allMissing.push(...missing);
  }
  // Backfill any source key the model dropped (returned in missing_keys or
  // simply absent) with the English passthrough. Without this, the renderer
  // emits a smaller file than en.ts and the i18n-diff CI gate flags drift.
  // Empty-string values trigger this path most often: Gemini skips them.
  for (const k of Object.keys(source)) {
    if (!(k in merged)) merged[k] = source[k];
  }
  return { translations: merged, missing: allMissing };
}

async function main() {
  const argv = process.argv.slice(2);
  const dryRun = argv.includes('--dry-run');
  const onlyMissing = argv.includes('--only-missing');
  let targets = TARGET_LOCALES;
  const localesIdx = argv.findIndex((a) => a === '--locales' || a.startsWith('--locales='));
  if (localesIdx !== -1) {
    const arg = argv[localesIdx];
    const csv = arg.includes('=') ? arg.split('=')[1] : argv[localesIdx + 1];
    targets = (csv || '').split(',').filter((x) => TARGET_LOCALES.includes(x));
    if (targets.length === 0) {
      console.error(`No valid locales in --locales arg. Valid: ${TARGET_LOCALES.join(', ')}`);
      process.exit(2);
    }
  }

  const envUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const secret = process.env.TRANSLATE_LOCALE_SECRET;
  if (!dryRun && (!envUrl || !secret)) {
    console.error('Missing EXPO_PUBLIC_SUPABASE_URL or TRANSLATE_LOCALE_SECRET');
    process.exit(2);
  }

  const enSrc = readFileSync(resolve(REPO_ROOT, 'mobile/src/i18n/locales/en.ts'), 'utf8');
  const svSrc = readFileSync(resolve(REPO_ROOT, 'mobile/src/i18n/locales/sv.ts'), 'utf8');
  const en = parseLocaleFile(enSrc);
  const sv = parseLocaleFile(svSrc);
  console.log(`Source: en (${Object.keys(en).length} keys) + sv anchor (${Object.keys(sv).length} keys)`);
  console.log(`Targets: ${targets.join(', ')}`);

  const { createHash } = await import('node:crypto');
  const sourceSha = createHash('sha1').update(enSrc).digest('hex').slice(0, 7);

  if (dryRun) {
    console.log('Dry run — no translation calls; exit.');
    return;
  }

  for (const target of targets) {
    console.log(`\n=== ${target} ===`);
    const outPath = resolve(REPO_ROOT, `mobile/src/i18n/locales/${target}.ts`);
    let source = en;
    if (onlyMissing && existsSync(outPath)) {
      const prev = parseLocaleFile(readFileSync(outPath, 'utf8'));
      source = Object.fromEntries(Object.entries(en).filter(([k]) => !(k in prev)));
      console.log(`--only-missing: ${Object.keys(source).length} of ${Object.keys(en).length} en keys to translate`);
      if (Object.keys(source).length === 0) {
        console.log('  nothing to do; skipping.');
        continue;
      }
    }
    const { translations, missing } = await translateOneLocale({
      targetLocale: target,
      source,
      sv,
      envUrl,
      secret,
    });

    let final = translations;
    if (onlyMissing && existsSync(outPath)) {
      const prev = parseLocaleFile(readFileSync(outPath, 'utf8'));
      final = { ...prev, ...translations };
    }
    writeFileSync(outPath, renderLocaleFile(target, final, { sourceSha }), 'utf8');
    console.log(`  wrote ${outPath} (${Object.keys(final).length} keys, ${missing.length} fell back to en)`);
  }
}

// Run main when executed directly, not when imported by tests.
// On Windows, process.argv[1] uses backslashes; import.meta.url uses
// file:// + forward slashes. Compare normalized paths.
const runDirectly = (() => {
  if (!process.argv[1]) return false;
  const argvUrl = 'file://' + process.argv[1].replace(/\\/g, '/');
  return import.meta.url === argvUrl || import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));
})();
if (runDirectly) {
  main().catch((err) => { console.error(err); process.exit(1); });
}
