#!/usr/bin/env node
// translate-locales — drives the translate_locale edge function to produce
// 12 mobile locale dictionaries from en.ts (source) + sv.ts (anchor).
//
// Usage:
//   node mobile/scripts/translate-locales.mjs                # all 12 locales
//   node mobile/scripts/translate-locales.mjs --locales fr,de
//   node mobile/scripts/translate-locales.mjs --only-missing # backfill mode
//   node mobile/scripts/translate-locales.mjs --dry-run      # parse only
//
// Env required (load from mobile/.env.local or process.env):
//   EXPO_PUBLIC_SUPABASE_URL  (or SUPABASE_URL)
//   TRANSLATE_LOCALE_SECRET
//
// Output: mobile/src/i18n/locales/<locale>.ts (overwrites unless --only-missing)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');

export const TARGET_LOCALES = [
  'ar', 'da', 'de', 'es', 'fa', 'fi', 'fr', 'it', 'nl', 'no', 'pl', 'pt',
];

/**
 * Parse a locale file's `Record<string, string>` literal into a JS object.
 * Order-preserving. Strips // line comments + /* block comments first.
 * Accepts single OR double-quoted keys and values; handles backslash-escaped
 * quotes inside values (don\'t).
 */
export function parseLocaleFile(src) {
  let s = src;
  s = s.replace(/\/\*[\s\S]*?\*\//g, '');
  s = s.replace(/^\s*\/\/.*$/gm, '');
  const out = {};
  // key: ('foo' | "foo")  : value: ('...' | "...")
  const re = /(['"])((?:\\.|(?!\1)[^\\])*)\1\s*:\s*(['"])((?:\\.|(?!\3)[^\\])*)\3\s*,?/g;
  let m;
  while ((m = re.exec(s)) !== null) {
    const key = m[2].replace(/\\(['"\\])/g, '$1');
    const val = m[4].replace(/\\(['"\\])/g, '$1');
    out[key] = val;
  }
  return out;
}

export function chunkObject(obj, size) {
  const out = [];
  const keys = Object.keys(obj);
  for (let i = 0; i < keys.length; i += size) {
    const chunk = {};
    for (const k of keys.slice(i, i + size)) chunk[k] = obj[k];
    out.push(chunk);
  }
  return out;
}

const CHUNK_SIZE = 80;

async function callEdge(envUrl, secret, payload) {
  const url = `${envUrl}/functions/v1/translate_locale`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-translate-secret': secret,
    },
    body: JSON.stringify(payload),
  });
  const text = await res.text();
  let body;
  try { body = JSON.parse(text); } catch { body = { error: 'non-json response', raw: text }; }
  return { status: res.status, body };
}

export function renderLocaleFile(locale, dict, opts = {}) {
  const { sourceSha = 'unknown' } = opts;
  const header = `// Auto-generated by mobile/scripts/translate-locales.mjs (${new Date().toISOString().slice(0, 10)}).
// Source: mobile/src/i18n/locales/en.ts (hash ${sourceSha}).
// Voice anchor: mobile/src/i18n/locales/sv.ts.
//
// To regenerate after en.ts grows:
//   node mobile/scripts/translate-locales.mjs --locales ${locale} --only-missing
//
// Append-only convention applies post-generation — never reorder keys.

export const ${locale}: Record<string, string> = {
`;
  const lines = [];
  for (const k of Object.keys(dict)) {
    const v = dict[k];
    // Pick the wrapping quote that doesn't require escaping the value.
    let wrap = "'";
    if (v.includes("'") && !v.includes('"')) wrap = '"';
    let escaped = v;
    if (wrap === "'") escaped = v.replace(/'/g, "\\'");
    else escaped = v.replace(/"/g, '\\"');
    const safeKey = k.replace(/'/g, "\\'");
    lines.push(`  '${safeKey}': ${wrap}${escaped}${wrap},`);
  }
  return header + lines.join('\n') + '\n};\n';
}

export async function translateOneLocale({
  targetLocale,
  source,
  sv,
  envUrl,
  secret,
  log = console.log,
  edgeCall = callEdge,
}) {
  const chunks = chunkObject(source, CHUNK_SIZE);
  const merged = {};
  const allMissing = [];
  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    const svRef = {};
    for (const k of Object.keys(chunk)) if (sv[k] !== undefined) svRef[k] = sv[k];
    log(`  [${targetLocale}] chunk ${i + 1}/${chunks.length} (${Object.keys(chunk).length} keys)`);
    const { status, body } = await edgeCall(envUrl, secret, {
      target_locale: targetLocale,
      source_keys: chunk,
      sv_reference: svRef,
      chunk_index: i,
      total_chunks: chunks.length,
    });
    if (status !== 200) {
      throw new Error(`[${targetLocale}] chunk ${i}: HTTP ${status} ${JSON.stringify(body).slice(0, 200)}`);
    }
    for (const k of Object.keys(body.translations || {})) merged[k] = body.translations[k];
    if (Array.isArray(body.missing_keys)) allMissing.push(...body.missing_keys);
  }
  return { translations: merged, missing: allMissing };
}

async function main() {
  const argv = process.argv.slice(2);
  const dryRun = argv.includes('--dry-run');
  const onlyMissing = argv.includes('--only-missing');
  let targets = TARGET_LOCALES;
  const localesIdx = argv.findIndex((a) => a === '--locales' || a.startsWith('--locales='));
  if (localesIdx !== -1) {
    const arg = argv[localesIdx];
    const csv = arg.includes('=') ? arg.split('=')[1] : argv[localesIdx + 1];
    targets = (csv || '').split(',').filter((x) => TARGET_LOCALES.includes(x));
    if (targets.length === 0) {
      console.error(`No valid locales in --locales arg. Valid: ${TARGET_LOCALES.join(', ')}`);
      process.exit(2);
    }
  }

  const envUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const secret = process.env.TRANSLATE_LOCALE_SECRET;
  if (!dryRun && (!envUrl || !secret)) {
    console.error('Missing EXPO_PUBLIC_SUPABASE_URL or TRANSLATE_LOCALE_SECRET');
    process.exit(2);
  }

  const enSrc = readFileSync(resolve(REPO_ROOT, 'mobile/src/i18n/locales/en.ts'), 'utf8');
  const svSrc = readFileSync(resolve(REPO_ROOT, 'mobile/src/i18n/locales/sv.ts'), 'utf8');
  const en = parseLocaleFile(enSrc);
  const sv = parseLocaleFile(svSrc);
  console.log(`Source: en (${Object.keys(en).length} keys) + sv anchor (${Object.keys(sv).length} keys)`);
  console.log(`Targets: ${targets.join(', ')}`);

  const { createHash } = await import('node:crypto');
  const sourceSha = createHash('sha1').update(enSrc).digest('hex').slice(0, 7);

  if (dryRun) {
    console.log('Dry run — no translation calls; exit.');
    return;
  }

  for (const target of targets) {
    console.log(`\n=== ${target} ===`);
    const outPath = resolve(REPO_ROOT, `mobile/src/i18n/locales/${target}.ts`);
    let source = en;
    if (onlyMissing && existsSync(outPath)) {
      const prev = parseLocaleFile(readFileSync(outPath, 'utf8'));
      source = Object.fromEntries(Object.entries(en).filter(([k]) => !(k in prev)));
      console.log(`--only-missing: ${Object.keys(source).length} of ${Object.keys(en).length} en keys to translate`);
      if (Object.keys(source).length === 0) {
        console.log('  nothing to do; skipping.');
        continue;
      }
    }
    const { translations, missing } = await translateOneLocale({
      targetLocale: target,
      source,
      sv,
      envUrl,
      secret,
    });

    let final = translations;
    if (onlyMissing && existsSync(outPath)) {
      const prev = parseLocaleFile(readFileSync(outPath, 'utf8'));
      final = { ...prev, ...translations };
    }
    writeFileSync(outPath, renderLocaleFile(target, final, { sourceSha }), 'utf8');
    console.log(`  wrote ${outPath} (${Object.keys(final).length} keys, ${missing.length} fell back to en)`);
  }
}

// Run main when executed directly, not when imported by tests.
// On Windows, process.argv[1] uses backslashes; import.meta.url uses
// file:// + forward slashes. Compare normalized paths.
const runDirectly = (() => {
  if (!process.argv[1]) return false;
  const argvUrl = 'file://' + process.argv[1].replace(/\\/g, '/');
  return import.meta.url === argvUrl || import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));
})();
if (runDirectly) {
  main().catch((err) => { console.error(err); process.exit(1); });
}
