import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Check } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { LazyImage } from '@/components/ui/lazy-image';
import { useLanguage } from '@/contexts/LanguageContext';
import { useOutfitGenerator, type GeneratedOutfit, type OutfitRequest } from '@/hooks/useOutfitGenerator';
import { useMarkOutfitWorn } from '@/hooks/useOutfits';
import { useSubscription } from '@/hooks/useSubscription';
import { hapticSuccess, hapticLight } from '@/lib/haptics';
import { EASE_CURVE, TAP_TRANSITION } from '@/lib/motion';

interface TodayOutfitCardProps {
  weather?: OutfitRequest['weather'];
  occasion: string;
  style?: string | null;
}

export function TodayOutfitCard({ weather, occasion, style }: TodayOutfitCardProps) {
  const { t, locale } = useLanguage();
  const navigate = useNavigate();
  const { generateOutfit, isGenerating } = useOutfitGenerator();
  const markWorn = useMarkOutfitWorn();
  const { isPremium } = useSubscription();

  const [outfit, setOutfit] = useState<GeneratedOutfit | null>(null);
  const [regenCount, setRegenCount] = useState(0);
  const [showNiceChoice, setShowNiceChoice] = useState(false);
  const [outfitKey, setOutfitKey] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const doGenerate = useCallback(async () => {
    try {
      const request: OutfitRequest = {
        occasion,
        style,
        locale,
        weather: weather || { precipitation: 'none', wind: 'low' },
      };
      const result = await generateOutfit(request);
      setOutfit(result);
      setOutfitKey((k) => k + 1);
    } catch (err) {
      console.error('Outfit generation failed:', err);
    }
  }, [occasion, style, locale, weather, generateOutfit]);

  // Auto-generate on mount
  useEffect(() => {
    if (!hasAutoGenerated) {
      setHasAutoGenerated(true);
      doGenerate();
    }
  }, [hasAutoGenerated, doGenerate]);

  const handleWearThis = async () => {
    if (!outfit) return;
    hapticSuccess();
    setShowNiceChoice(true);
    setTimeout(() => setShowNiceChoice(false), 2500);
    const garmentIds = outfit.items.map((i) => i.garment.id);
    markWorn.mutate({ outfitId: outfit.id, garmentIds, occasion: outfit.occasion });
  };

  const handleTryAnother = async () => {
    if (!isPremium && regenCount >= 3) return;
    hapticLight();
    setRegenCount((c) => c + 1);
    await doGenerate();
  };

  // Skeleton loading state
  if (isGenerating && !outfit) {
    return (
      <div className="rounded-2xl bg-foreground/[0.02] border border-border/30 p-4 space-y-4">
        <p className="text-xs text-muted-foreground/70 font-medium">{t('home.todays_outfit')}</p>
        <div className="grid grid-cols-2 gap-1.5">
          {[0, 1, 2, 3].map((i) => (
            <Skeleton key={i} className="aspect-[4/5] rounded-xl" />
          ))}
        </div>
        <div className="flex gap-3">
          <Skeleton className="h-12 flex-1 rounded-xl" />
          <Skeleton className="h-12 flex-1 rounded-xl" />
        </div>
      </div>
    );
  }

  if (!outfit) return null;

  const showUpgradeHint = !isPremium && regenCount >= 3;

  return (
    <div className="rounded-2xl bg-foreground/[0.02] border border-border/30 p-4 space-y-4">
      <p className="text-xs text-muted-foreground/70 font-medium">{t('home.todays_outfit')}</p>

      {/* Garment grid */}
      <AnimatePresence mode="wait">
        <motion.div
          key={outfitKey}
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.96 }}
          transition={{ duration: 0.35, ease: EASE_CURVE }}
          className="grid grid-cols-2 gap-1.5"
        >
          {outfit.items.slice(0, 4).map((item) => (
            <div
              key={item.garment.id}
              onClick={() => navigate(`/wardrobe/${item.garment.id}`)}
              className="cursor-pointer active:scale-[0.97] transition-transform"
            >
              <LazyImage
                imagePath={item.garment.image_path}
                alt={item.garment.title}
                aspectRatio="4/5"
                className="rounded-xl"
              />
            </div>
          ))}
        </motion.div>
      </AnimatePresence>

      {/* Shimmer overlay during regeneration */}
      {isGenerating && outfit && (
        <div className="absolute inset-0 rounded-2xl bg-background/40 backdrop-blur-[2px] flex items-center justify-center">
          <Sparkles className="w-6 h-6 text-accent animate-pulse" />
        </div>
      )}

      {/* Buttons */}
      <div className="flex gap-3">
        <Button
          onClick={handleWearThis}
          disabled={markWorn.isPending}
          className="flex-1 h-12 text-sm font-semibold bg-accent text-accent-foreground hover:bg-accent/90 rounded-xl"
        >
          <Check className="w-4 h-4 mr-2" />
          {t('home.wear_this')}
        </Button>
        <motion.div className="flex-1" whileTap={{ scale: 0.97 }} transition={TAP_TRANSITION}>
          <Button
            variant="outline"
            onClick={handleTryAnother}
            disabled={isGenerating || showUpgradeHint}
            className="w-full h-12 text-sm font-semibold rounded-xl border-border/50"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            {t('home.try_another')}
          </Button>
        </motion.div>
      </div>

      {/* Nice choice feedback */}
      <AnimatePresence>
        {showNiceChoice && (
          <motion.p
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3, ease: EASE_CURVE }}
            className="text-xs text-center text-accent font-medium"
          >
            {t('home.nice_choice')}
          </motion.p>
        )}
      </AnimatePresence>

      {/* Inline upgrade hint */}
      {showUpgradeHint && (
        <p className="text-xs text-center text-muted-foreground">
          {t('home.unlock_unlimited')}{' '}
          <button onClick={() => navigate('/pricing')} className="text-accent underline underline-offset-2">
            →
          </button>
        </p>
      )}
    </div>
  );
}
