import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Check, Palette } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { LazyImage } from '@/components/ui/lazy-image';
import { OutfitGenerationState } from '@/components/ui/OutfitGenerationState';
import { AILoadingOverlay } from '@/components/ui/AILoadingOverlay';
import { useLanguage } from '@/contexts/LanguageContext';
import { useOutfitGenerator, type GeneratedOutfit, type OutfitRequest } from '@/hooks/useOutfitGenerator';
import { useMarkOutfitWorn } from '@/hooks/useOutfits';
import { useSubscription } from '@/hooks/useSubscription';
import { hapticSuccess, hapticLight } from '@/lib/haptics';
import { EASE_CURVE, TAP_TRANSITION } from '@/lib/motion';
import { getPreferredGarmentImagePath } from '@/lib/garmentImage';

interface TodayOutfitCardProps {
  weather?: OutfitRequest['weather'];
  occasion: string;
  style?: string | null;
}

export function TodayOutfitCard({ weather, occasion, style }: TodayOutfitCardProps) {
  const { t, locale } = useLanguage();
  const navigate = useNavigate();
  const { generateOutfit, isGenerating } = useOutfitGenerator();
  const markWorn = useMarkOutfitWorn();
  const { isPremium } = useSubscription();

  const [outfit, setOutfit] = useState<GeneratedOutfit | null>(null);
  const [regenCount, setRegenCount] = useState(0);
  const [showNiceChoice, setShowNiceChoice] = useState(false);
  const [outfitKey, setOutfitKey] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const doGenerate = useCallback(async () => {
    try {
      const request: OutfitRequest = {
        occasion,
        style,
        locale,
        weather: weather || { precipitation: 'none', wind: 'low' },
      };
      const result = await generateOutfit(request);
      setOutfit(result);
      setOutfitKey((k) => k + 1);
    } catch (err) {
      console.error('Outfit generation failed:', err);
    }
  }, [occasion, style, locale, weather, generateOutfit]);

  // Auto-generate on mount
  useEffect(() => {
    if (!hasAutoGenerated) {
      setHasAutoGenerated(true);
      doGenerate();
    }
  }, [hasAutoGenerated, doGenerate]);

  const handleWearThis = async () => {
    if (!outfit) return;
    hapticSuccess();
    setShowNiceChoice(true);
    setTimeout(() => setShowNiceChoice(false), 2500);
    const garmentIds = outfit.items.map((i) => i.garment.id);
    markWorn.mutate({ outfitId: outfit.id, garmentIds, occasion: outfit.occasion });
  };

  const handleTryAnother = async () => {
    if (!isPremium && regenCount >= 3) return;
    hapticLight();
    setRegenCount((c) => c + 1);
    await doGenerate();
  };

  // Loading state with outfit generation skeleton
  if (isGenerating && !outfit) {
    return (
      <div className="space-y-1">
        <p className="label-editorial">{t('home.todays_outfit')}</p>
        <OutfitGenerationState variant="compact" subtitle={occasion} />
      </div>
    );
  }

  if (!outfit) return null;

  const showUpgradeHint = !isPremium && regenCount >= 3;

  return (
    <div className="rounded-2xl surface-hero p-5 space-y-4 relative overflow-hidden">
        <p className="label-editorial">{t('home.todays_outfit')}</p>

      {/* Garment grid — swipe right to wear */}
      <AnimatePresence mode="wait">
        <motion.div
          key={outfitKey}
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1, x: 0 }}
          exit={{ opacity: 0, scale: 0.96 }}
          transition={{ duration: 0.35, ease: EASE_CURVE }}
          drag="x"
          dragConstraints={{ left: 0, right: 0 }}
          dragElastic={0.3}
          onDragEnd={(_, info) => {
            if (info.offset.x > 100 && !markWorn.isPending) {
              handleWearThis();
            }
          }}
          className="grid grid-cols-2 gap-2 cursor-grab active:cursor-grabbing"
        >
          {outfit.items.slice(0, 4).map((item) => (
            <div
              key={item.garment.id}
              onClick={() => navigate(`/wardrobe/${item.garment.id}`)}
              className="cursor-pointer active:scale-[0.97] transition-transform"
            >
              <LazyImage
                imagePath={getPreferredGarmentImagePath(item.garment)}
                alt={item.garment.title}
                aspectRatio="3/4"
                className="rounded-xl"
              />
            </div>
          ))}
        </motion.div>
      </AnimatePresence>


      {/* Regeneration overlay with mini AI loading */}
      {isGenerating && outfit && (
        <div className="absolute inset-0 rounded-2xl bg-background/60 backdrop-blur-[2px] flex items-center justify-center z-10">
          <AILoadingOverlay
            variant="inline"
            phases={[
              { icon: Sparkles, label: t('home.shuffling') || 'Shuffling...', duration: 1500 },
              { icon: Palette, label: t('home.restyling') || 'Restyling...', duration: 0 },
            ]}
            className="py-4"
          />
        </div>
      )}

      {/* Buttons */}
      <div className="flex gap-3">
        <Button
          onClick={handleWearThis}
          disabled={markWorn.isPending}
          className="flex-1 h-11 text-[0.8125rem] font-semibold bg-accent text-accent-foreground hover:bg-accent/90 rounded-xl tracking-[-0.01em]"
        >
          <Check className="w-4 h-4 mr-2" />
          {t('home.wear_this')}
        </Button>
        <motion.div className="flex-1" whileTap={{ scale: 0.97 }} transition={TAP_TRANSITION}>
          <Button
            variant="outline"
            onClick={handleTryAnother}
            disabled={isGenerating || showUpgradeHint}
            className="w-full h-11 text-[0.8125rem] font-semibold rounded-xl border-border/50 tracking-[-0.01em]"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            {t('home.try_another')}
          </Button>
        </motion.div>
      </div>

      {/* Nice choice feedback */}
      <AnimatePresence>
        {showNiceChoice && (
          <motion.p
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3, ease: EASE_CURVE }}
            className="text-xs text-center text-accent font-medium"
          >
            {t('home.nice_choice')}
          </motion.p>
        )}
      </AnimatePresence>

      {/* View outfit details link */}
      {outfit && (
        <button
          onClick={() => navigate(`/outfits/${outfit.id}`)}
          className="text-[11px] text-center text-muted-foreground/50 hover:text-foreground transition-colors w-full tracking-wide"
        >
          {t('home.see_details')} →
        </button>
      )}

      {/* Inline upgrade hint */}
      {showUpgradeHint && (
        <p className="text-xs text-center text-muted-foreground">
          {t('home.unlock_unlimited')}{' '}
          <button onClick={() => navigate('/pricing')} className="text-accent underline underline-offset-2">
            →
          </button>
        </p>
      )}
    </div>
  );
}
