// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function requireEnv(name: 'VITE_SUPABASE_URL' | 'VITE_SUPABASE_PUBLISHABLE_KEY'): string {
  const value = import.meta.env[name];

  if (!value) {
    throw new Error(
      `Missing required Supabase environment variable: ${name}. `
      + 'Set it in your frontend environment before starting BURS.'
    );
  }

  return value;
}

export const supabaseUrl = requireEnv('VITE_SUPABASE_URL');
export const supabasePublishableKey = requireEnv('VITE_SUPABASE_PUBLISHABLE_KEY');

export const supabase = createClient<Database>(
  supabaseUrl,
  supabasePublishableKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
