// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL 
  || 'https://dvrdxjmnydcjzpcwjxgv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY 
  || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cmR4am1ueWRjanpwY3dqeGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMTY0NTcsImV4cCI6MjA4NDc5MjQ1N30.hBeJlcIRvvrQHwFNgGBvqsmM76hoOKHkXJo2dat-AnE';

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
